### ISSUE TITLE
Which LMFIT version was used?

### ISSUE THREAD

**Issue by vzickus** [dpscience/DLTReconvolution#1]
When trying to run the test case (no modifications after cloning), I get an error associated with lmfit. Could you list the versions of packages you used when distributing the latest version?

```
simulating spectrum & irf data...
[108.0, 385.0, 2200.0]
[0.85, 0.147, 0.003]
counts: 4998983.000000004
calculating individual fit weights...


reconvolution fitting with 3 components...

Traceback (most recent call last):
  File "DReconvolutionProc.py", line 1046, in <module>
    fitModelDecay = Model(ExpDecay_3)
  File "/home/vytas/anaconda3/lib/python3.7/site-packages/lmfit/model.py", line 274, in __init__
    self._parse_params()
  File "/home/vytas/anaconda3/lib/python3.7/site-packages/lmfit/model.py", line 480, in _parse_params
    if fpar.default == fpar.empty:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by aravind-j** [comment]
I am also getting the same lmfit error with WinPython.

```
runfile('C:/DLTReconvolution-master/DReconvolutionProc.py', wdir='C:/DLTReconvolution-master')
Reloaded modules: DReconvolutionModel, DReconvolutionInput, DReconvolutionSpecSimulator
simulating spectrum & irf data...
[108.0, 385.0, 2200.0]
[0.85, 0.147, 0.003]
counts: 5000932.000000008
calculating individual fit weights...


reconvolution fitting with 3 components...

Traceback (most recent call last):

  File "<ipython-input-9-da1133ae3b2b>", line 1, in <module>
    runfile('C:/DLTReconvolution-master/DReconvolutionProc.py', wdir='C:/DLTReconvolution-master')

  File "C:\Software - Portable\WPy64-3810\python-3.8.1.amd64\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Software - Portable\WPy64-3810\python-3.8.1.amd64\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/DLTReconvolution-master/DReconvolutionProc.py", line 1046, in <module>
    fitModelDecay = Model(ExpDecay_3)

  File "C:\Software - Portable\WPy64-3810\python-3.8.1.amd64\lib\site-packages\lmfit\model.py", line 274, in __init__
    self._parse_params()

  File "C:\Software - Portable\WPy64-3810\python-3.8.1.amd64\lib\site-packages\lmfit\model.py", line 480, in _parse_params
    if fpar.default == fpar.empty:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by kitchenknif** [comment]
Latest version of lmfit that works with the current version 7662ec7 is [0.9.13](https://github.com/lmfit/lmfit-py/releases/tag/0.9.13)

After that something broke, I'll try to figure it out if I have time.
